name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"



[env.production.vars]
GITHUB_ID = "Ov23liQvVt8Y8QavKb5W"
GITHUB_OWNER = "SecNN"
GITHUB_REPO = "navsphere-data"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://nav.secnn.com/api/auth"
NEXT_PUBLIC_API_URL="https://nav.secnn.com"

